<?php
/**
 * Batch administration page adapter.
 *
 * @package ReturnTag\TagCore
 */

declare(strict_types=1);

namespace ReturnTag\TagCore\Admin;

use ReturnTag\TagCore\Infrastructure\Migration\SchemaState;

/**
 * Registers and renders the React-owned Batch administration surface.
 */
final class BatchAdminPage {
	public const PAGE_SLUG = 'tagcore-batches';

	private const SCRIPT_HANDLE = 'returntag-tagcore-admin';

	/**
	 * WordPress page hooks assigned during menu registration.
	 *
	 * @var list<string>
	 */
	private array $page_hooks = array();

	/**
	 * Create the page adapter.
	 *
	 * @param string      $plugin_dir Absolute plugin directory.
	 * @param SchemaState $schema_state Schema readiness.
	 */
	public function __construct(
		private readonly string $plugin_dir,
		private readonly SchemaState $schema_state
	) {
	}

	/**
	 * Register the menu and asset hooks.
	 */
	public function register_hooks(): void {
		add_action( 'admin_menu', array( $this, 'register_menu' ) );
		add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_assets' ) );
	}

	/**
	 * Register the TagCore top-level Batch page.
	 */
	public function register_menu(): void {
		$top_level_hook = add_menu_page(
			__( 'TagCore Batches', 'tagcore' ),
			__( 'TagCore', 'tagcore' ),
			Capability::MANAGE_BATCHES,
			self::PAGE_SLUG,
			array( $this, 'render' ),
			'dashicons-tag',
			58
		);

		$batch_hook = add_submenu_page(
			self::PAGE_SLUG,
			__( 'TagCore Batches', 'tagcore' ),
			__( 'Batches', 'tagcore' ),
			Capability::MANAGE_BATCHES,
			self::PAGE_SLUG,
			array( $this, 'render' )
		);

		foreach ( array( $top_level_hook, $batch_hook ) as $page_hook ) {
			if ( is_string( $page_hook ) ) {
				$this->page_hooks[] = $page_hook;
			}
		}
	}

	/**
	 * Render the administrative root or a fail-closed schema notice.
	 */
	public function render(): void {
		if ( ! current_user_can( Capability::MANAGE_BATCHES ) ) {
			wp_die(
				esc_html__( 'You are not allowed to manage ReturnTag batches.', 'tagcore' ),
				esc_html__( 'Access denied', 'tagcore' ),
				array( 'response' => 403 )
			);
		}

		echo '<div class="wrap returntag-admin">';

		if ( ! $this->schema_state->is_current() ) {
			echo '<div class="notice notice-error"><p>';
			esc_html_e( 'TagCore batch administration is unavailable until database preparation completes.', 'tagcore' );
			echo '</p></div></div>';
			return;
		}

		echo '<div id="returntag-admin-root"></div></div>';
	}

	/**
	 * Enqueue the compiled WordPress-native administration bundle.
	 *
	 * @param string $hook_suffix Current WordPress administration page hook.
	 */
	public function enqueue_assets( string $hook_suffix ): void {
		if ( ! in_array( $hook_suffix, $this->page_hooks, true ) || ! $this->schema_state->is_current() ) {
			return;
		}

		$asset_file  = $this->plugin_dir . '/build/admin/admin.tsx.asset.php';
		$script_file = $this->plugin_dir . '/build/admin/admin.tsx.js';
		$style_file  = $this->plugin_dir . '/build/admin/admin.tsx.css';

		if ( ! is_readable( $asset_file ) || ! is_readable( $script_file ) || ! is_readable( $style_file ) ) {
			return;
		}

		/**
		 * Compiled dependency metadata generated by @wordpress/scripts.
		 *
		 * @var array{dependencies: list<string>, version: string} $asset
		 */
		$asset = require $asset_file;

		wp_enqueue_script(
			self::SCRIPT_HANDLE,
			plugins_url( 'build/admin/admin.tsx.js', $this->plugin_dir . '/tagcore.php' ),
			$asset['dependencies'],
			$asset['version'],
			true
		);
		wp_enqueue_style(
			self::SCRIPT_HANDLE,
			plugins_url( 'build/admin/admin.tsx.css', $this->plugin_dir . '/tagcore.php' ),
			array( 'wp-components' ),
			$asset['version']
		);
		wp_set_script_translations( self::SCRIPT_HANDLE, 'tagcore', $this->plugin_dir . '/languages' );

		$user = wp_get_current_user();
		wp_localize_script(
			self::SCRIPT_HANDLE,
			'returntagTagCoreAdmin',
			array(
				'nonce'       => wp_create_nonce( 'wp_rest' ),
				'restPath'    => '/tagcore/v1',
				'currentUser' => $user->display_name,
				'currentTime' => gmdate( DATE_ATOM ),
				'listUrl'     => admin_url( 'admin.php?page=' . self::PAGE_SLUG ),
				'createUrl'   => admin_url( 'admin.php?page=' . self::PAGE_SLUG . '&view=create' ),
			)
		);
	}
}
