<?php
/**
 * Read-only Tag administration page adapter.
 *
 * @package ReturnTag\TagCore
 */

declare(strict_types=1);

namespace ReturnTag\TagCore\Admin;

use ReturnTag\TagCore\Infrastructure\Migration\SchemaState;

/**
 * Registers and renders the React-owned Tag search surface.
 */
final class TagAdminPage {
	public const PAGE_SLUG = 'tagcore-tags';

	private const SCRIPT_HANDLE = 'returntag-tagcore-admin';

	/**
	 * WordPress page hook assigned during menu registration.
	 *
	 * @var string|null
	 */
	private ?string $page_hook = null;

	/**
	 * Create the page adapter.
	 *
	 * @param string      $plugin_dir Absolute plugin directory.
	 * @param SchemaState $schema_state Schema readiness.
	 */
	public function __construct(
		private readonly string $plugin_dir,
		private readonly SchemaState $schema_state
	) {
	}

	/**
	 * Register menu and asset hooks.
	 */
	public function register_hooks(): void {
		add_action( 'admin_menu', array( $this, 'register_menu' ) );
		add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_assets' ) );
	}

	/**
	 * Register the dedicated Tags submenu.
	 */
	public function register_menu(): void {
		$page_hook = add_submenu_page(
			BatchAdminPage::PAGE_SLUG,
			__( 'TagCore Tags', 'tagcore' ),
			__( 'Tags', 'tagcore' ),
			Capability::MANAGE_TAGS,
			self::PAGE_SLUG,
			array( $this, 'render' )
		);

		$this->page_hook = is_string( $page_hook ) ? $page_hook : null;
	}

	/**
	 * Render the administration root or a fail-closed Schema notice.
	 */
	public function render(): void {
		if ( ! current_user_can( Capability::MANAGE_TAGS ) ) {
			wp_die(
				esc_html__( 'You are not allowed to search ReturnTag tags.', 'tagcore' ),
				esc_html__( 'Access denied', 'tagcore' ),
				array( 'response' => 403 )
			);
		}

		echo '<div class="wrap returntag-admin">';

		if ( ! $this->schema_state->is_current() ) {
			echo '<div class="notice notice-error"><p>';
			esc_html_e( 'TagCore Tag administration is unavailable until database preparation completes.', 'tagcore' );
			echo '</p></div></div>';
			return;
		}

		echo '<div id="returntag-admin-root"></div></div>';
	}

	/**
	 * Enqueue the shared compiled administration bundle.
	 *
	 * @param string $hook_suffix Current WordPress administration page hook.
	 */
	public function enqueue_assets( string $hook_suffix ): void {
		if ( $hook_suffix !== $this->page_hook || ! $this->schema_state->is_current() ) {
			return;
		}

		$asset_file  = $this->plugin_dir . '/build/admin/admin.tsx.asset.php';
		$script_file = $this->plugin_dir . '/build/admin/admin.tsx.js';
		$style_file  = $this->plugin_dir . '/build/admin/admin.tsx.css';

		if ( ! is_readable( $asset_file ) || ! is_readable( $script_file ) || ! is_readable( $style_file ) ) {
			return;
		}

		/**
		 * Compiled dependency metadata generated by @wordpress/scripts.
		 *
		 * @var array{dependencies: list<string>, version: string} $asset
		 */
		$asset = require $asset_file;

		wp_enqueue_script(
			self::SCRIPT_HANDLE,
			plugins_url( 'build/admin/admin.tsx.js', $this->plugin_dir . '/tagcore.php' ),
			$asset['dependencies'],
			$asset['version'],
			true
		);
		wp_enqueue_style(
			self::SCRIPT_HANDLE,
			plugins_url( 'build/admin/admin.tsx.css', $this->plugin_dir . '/tagcore.php' ),
			array( 'wp-components' ),
			$asset['version']
		);
		wp_set_script_translations( self::SCRIPT_HANDLE, 'tagcore', $this->plugin_dir . '/languages' );

		$user = wp_get_current_user();
		wp_localize_script(
			self::SCRIPT_HANDLE,
			'returntagTagCoreAdmin',
			array(
				'nonce'                 => wp_create_nonce( 'wp_rest' ),
				'restPath'              => '/tagcore/v1',
				'currentUser'           => $user->display_name,
				'currentTime'           => gmdate( DATE_ATOM ),
				'listUrl'               => admin_url( 'admin.php?page=' . BatchAdminPage::PAGE_SLUG ),
				'createUrl'             => admin_url( 'admin.php?page=' . BatchAdminPage::PAGE_SLUG . '&view=create' ),
				'tagsUrl'               => admin_url( 'admin.php?page=' . self::PAGE_SLUG ),
				'finderReportsUrl'      => admin_url( 'admin.php?page=' . OperationsAdminPage::FINDER_REPORTS_SLUG ),
				'usersUrl'              => admin_url( 'admin.php?page=' . OperationsAdminPage::USERS_SLUG ),
				'canManageTags'         => current_user_can( Capability::MANAGE_TAGS ),
				'canManageTagLifecycle' => current_user_can( Capability::MANAGE_TAG_LIFECYCLE ),
				'canManageDisputes'     => current_user_can( Capability::MANAGE_DISPUTES ),
				'canViewUsers'          => current_user_can( Capability::VIEW_USERS ),
				'canViewAudit'          => current_user_can( Capability::VIEW_AUDIT_LOGS ),
				'canEditUsers'          => current_user_can( 'edit_users' ),
				'surface'               => 'tags',
			)
		);
	}
}
