version: 2
updates:
  - package-ecosystem: composer
    directory: /plugin/tagcore
    schedule:
      interval: weekly
    labels:
      - dependencies
      - php

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - javascript

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - ci
